# Generated by Django 4.0.2 on 2022-04-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_head', models.CharField(default='', max_length=200)),
                ('appointment_details', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_wallet_address', models.CharField(default='', max_length=200)),
                ('doctor_name', models.CharField(default='', max_length=200)),
                ('doctor_resi_address', models.CharField(default='', max_length=200)),
                ('doctor_contact_number', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_wallet_address', models.CharField(default='', max_length=200)),
                ('patient_name', models.CharField(default='', max_length=200)),
                ('patient_resi_address', models.CharField(default='', max_length=200)),
                ('patient_contact_number', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
